/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagement;

import java.awt.Toolkit;

/**
 *
 * @author moham
 */
public class studentresult extends javax.swing.JFrame {

    /**
     * Creates new form studentresult
     */
    public studentresult() {
        initComponents();
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TWOTWO = new javax.swing.JButton();
        ONEONE = new javax.swing.JButton();
        ONETWO = new javax.swing.JButton();
        FOURTWO = new javax.swing.JButton();
        TWOONE = new javax.swing.JButton();
        THREEONE = new javax.swing.JButton();
        THREETWO = new javax.swing.JButton();
        FOURONE = new javax.swing.JButton();
        BACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESULT DATA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        TWOTWO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TWOTWO.setText("2nd YEAR 2nd SEMESTER");
        TWOTWO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWOTWOActionPerformed(evt);
            }
        });

        ONEONE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ONEONE.setText("1st YEAR 1st SEMESTER");
        ONEONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONEONEActionPerformed(evt);
            }
        });

        ONETWO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ONETWO.setText("1st YEAR 2nd SEMESTER");
        ONETWO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONETWOActionPerformed(evt);
            }
        });

        FOURTWO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FOURTWO.setText("4th YEAR 2nd SEMESTER");
        FOURTWO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOURTWOActionPerformed(evt);
            }
        });

        TWOONE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TWOONE.setText("2nd YEAR 1st SEMESTER");
        TWOONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWOONEActionPerformed(evt);
            }
        });

        THREEONE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        THREEONE.setText("3rd YEAR 1st SEMESTER");
        THREEONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THREEONEActionPerformed(evt);
            }
        });

        THREETWO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        THREETWO.setText("3rd YEAR 2nd SEMESTER");
        THREETWO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THREETWOActionPerformed(evt);
            }
        });

        FOURONE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FOURONE.setText("4th YEAR 1st SEMESTER");
        FOURONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOURONEActionPerformed(evt);
            }
        });

        BACK.setBackground(new java.awt.Color(0, 0, 255));
        BACK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FOURTWO, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(THREETWO, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(THREEONE, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TWOONE, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ONETWO, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ONEONE, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TWOTWO, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FOURONE, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(BACK)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ONEONE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ONETWO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TWOONE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TWOTWO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(THREEONE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(THREETWO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FOURONE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FOURTWO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       //to go resultadder2 jframe
    private void ONETWOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONETWOActionPerformed
        resultadder2 ob = new resultadder2();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_ONETWOActionPerformed
          //to go resultadder6 jframe
    private void THREETWOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THREETWOActionPerformed
       resultadder6 ob = new resultadder6();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_THREETWOActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        dispose();
        AdminInfo ob=new AdminInfo();
        ob.setVisible(true);
        
        
    }//GEN-LAST:event_BACKActionPerformed
     //to go resultadder jframe
    private void ONEONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONEONEActionPerformed
        dispose();
        resultadder ob =new resultadder();
        ob.setVisible(true);
    }//GEN-LAST:event_ONEONEActionPerformed
        //to go resultadder3 jframe
    private void TWOONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWOONEActionPerformed
       dispose();
        resultadder3 ob2=new resultadder3();
        ob2.setVisible(true);
        
        
    }//GEN-LAST:event_TWOONEActionPerformed
         //to go resultadder4 jframe
    private void TWOTWOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWOTWOActionPerformed
        resultadder4 ob = new resultadder4();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_TWOTWOActionPerformed
         //to go resultadder5 jframe
    private void THREEONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THREEONEActionPerformed
      resultadder5 ob = new resultadder5();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_THREEONEActionPerformed
       //to go resultadder7 jframe
    private void FOURONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOURONEActionPerformed
        resultadder7 ob = new resultadder7();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_FOURONEActionPerformed
        //to go resultadder8 jframe
    private void FOURTWOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOURTWOActionPerformed
        resultadder8 ob = new resultadder8();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_FOURTWOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentresult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton FOURONE;
    private javax.swing.JButton FOURTWO;
    private javax.swing.JButton ONEONE;
    private javax.swing.JButton ONETWO;
    private javax.swing.JButton THREEONE;
    private javax.swing.JButton THREETWO;
    private javax.swing.JButton TWOONE;
    private javax.swing.JButton TWOTWO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
   private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.jpg")));

    }
}
